config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users

  get '/users', to: 'users#index'

  post '/reigns', to: 'users#update'

  root 'welcome#index'

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get '/reigns', to: 'reigns#index'

  get '/:user_id/check_monarch', to: 'users#check_if_still_monarch'

  get '/out', to: 'refuse#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reign.rb
class Reign < ApplicationRecord
  belongs_to :user
  validates :weapon, :format => { with: /\A[a-zA-Z]+\z/ , :message => 'Name must be one word, no special characters' }


  # scope :top_ten_by_reigns, -> { includes(:user).where.not(duration: nil).order(duration: :desc).limit(10) }

  # def self.transition(new_monarch_id)
  #   previous_reign = Reign.last
  #   previous_reign.finished = DateTime.now
  #   previous_reign.duration = previous_reign.finished - previous_reign.created_at
  #   previous_reign.save
  #
  #   User.find(previous_reign.user_id).update_total_reign(previous_reign.duration)
  #
  #   reign = Reign.create(user_id: new_monarch_id)
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reigns

  def self.create_with_omniauth(auth)
    user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
    user.password = auth['uid']
    user.first_name = auth['info']['first_name']
    user.last_name = auth['info']['last_name']
    user.email = auth['info']['email']
    user.age_range = auth.extra.raw_info.age_range
    user.link = auth.extra.raw_info.link
    picture = auth['info']['image']
    user.picture = picture.slice(0..(picture.index('?')))+"width=200&height=200"
    user.locale = auth.extra.raw_info.locale
    user.gender = auth.extra.raw_info.gender
    user.total_reign ||= 0
    user.save!

    if User.exists?(user)
      user
    else
      user.save!
      user
    end
  end

  def update_total_reign
    actual_duration = Reign.where(user_id: id).sum { |r| r.duration.present? ? r.duration : 0 }
    update_attribute(:total_reign, actual_duration)
  end

  def ranking_by_duration
    User.where("total_reign > ?", total_reign).count + 1
  end

  def ranking_by_reign_number
    users = User.joins(:reigns).group(:id).order("count(*) desc")
    users.each_with_index do |user, index|
      if user.id == id
        return index + 1
      end
    end
  end

  def title
    return 'Monarch' unless ['male', 'female'].include? gender
    gender == 'male' ? 'King' : 'Queen'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def require_signin!
    unless current_user
      # flash[:message] = "Please sign in to access this page"
      redirect_to root_path
    end
  end
  helper_method :require_signin!

  def current_reign
    @current_reign ||= Reign.last
  end

  helper_method :current_reign

  def previous_reign
    Reign.where('id < ?', current_reign.id).order(id: :desc).first
  end

  helper_method :previous_reign

  def current_monarch
    current_monarch_id = Reign.last.user_id
    @current_monarch ||= User.find(current_monarch_id)
  end

  helper_method :current_monarch

  def usurper
    User.find(usurper_reign.user_id)
  end

  helper_method :usurper

  def deadly_weapon
    usurper_reign.weapon
  end

  helper_method :deadly_weapon

  def usurper_reign
    @usurper_reign ||= Reign.where('id > ?', last_reign.id).order(:id).first
  end

  def last_reign
    @last_reign ||= current_user.reigns.last
  end
end

app/controllers/refuse_controller.rb
class RefuseController < ApplicationController
  def index
    session[:user_id] = nil
    render :index
  end
end

app/controllers/reigns_controller.rb
class ReignsController < ApplicationController
  def index
    @reigns = Reign.order(created_at: :desc).page(params[:page])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if request.env['omniauth.auth']
      user = User.create_with_omniauth(request.env['omniauth.auth'])
      session[:user_id] = user.id
      redirect_to users_path
    else
      user = User.find_by_email(params[:email])
      user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin!

  def index
    @reign = Reign.new
    if current_user.id == 189 || current_user.id == 194 || current_user.id == 238
      redirect_to out_path
    end
  end

  def show
  end

  def update
    previous_reign = Reign.last

    begin
      @reign = Reign.create!(user_id: current_user.id, weapon: params[:reign][:weapon])

      previous_reign.finished = DateTime.now
      previous_reign.duration = previous_reign.finished - previous_reign.created_at
      previous_reign.save

      User.find(previous_reign.user_id).update_total_reign
      redirect_to users_path
    rescue Exception => e
      flash[:message] = e.message
      redirect_to users_path
    end
  end

  def check_if_still_monarch
    render json: current_monarch.id == params[:user_id].to_i
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to users_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def humanize(secs)
    [[60, :secs], [60, :mins], [24, :hours], [1000, :days]].map{ |count, name|
    if secs > 0
      secs, n = secs.divmod(count)
      "#{n.to_i} #{name}"
    end
    }.compact.reverse.join(' ')
  end

  def top_ten_by_duration
    User.where.not(total_reign: 0).order(total_reign: :desc).limit(10)
  end

  def top_ten_by_reign_number
    User.joins(:reigns)
        .where('reigns.finished is not null')
        .select('users.id, users.first_name, users.picture, users.gender, count(*) as reigns_count')
        .group(:id)
        .order("reigns_count desc")
        .limit(10)
  end

  def current_reign
    Reign.last
  end

end

app/helpers/refuse_helper.rb
module RefuseHelper
end

app/helpers/reigns_helper.rb
module ReignsHelper
  def random_number
    rand(1...8)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Kingdom of The Hill</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900italic,700italic,400italic,300italic,100italic,900,700,300,100' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Press+Start+2P|Lemon|Kavoon|Poiret+One|Comfortaa|Lato|Ubuntu|Oxygen|Asap' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Patua+One|Sigmar+One|Chewy|Bevan|Luckiest+Guy|Fugaz+One|Carter+One|Slackey|Bowlby+One+SC|Finger+Paint|Titan+One|Kavoon|Londrina+Outline' rel='stylesheet' type='text/css'>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','//connect.facebook.net/en_US/fbevents.js');
    // Insert Your Facebook Pixel ID below.
    fbq('init', '1520469408256474');
    fbq('track', 'PageView');
    fbq('track', 'ViewContent');
    fbq('track', 'InitiateCheckout');
    fbq('track', 'Lead');

    </script>
    <!-- Insert Your Facebook Pixel ID below. -->
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=FB_PIXEL_ID&amp;ev=PageView&amp;noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->
  </head>

  <body>

    <% flash.each do |key, msg| %>
      <%= content_tag :div, msg, id: key, style: "color: red;"%>
    <% end %>

    <img class="cloud cloud-1" src="/assets/cloud1" alt="cloud" />
    <img class="cloud cloud-2" src="/assets/cloud2" alt="cloud" />
    <img class="cloud cloud-3" src="/assets/cloud3" alt="cloud" />
    <img class="cloud cloud-4" src="/assets/cloud2" alt="cloud" />
    <img class= "hill-image" src="/assets/hill-with-castle-lighter.png" alt="The Hill" />

    <nav>
      <h1 class="kingdom-title"> <a href="<%="#{'/'}"%>">The Kingdom of the Hill</h1>
      <!-- <img src="/assets/facebook-circle.png" alt="facebook-page-link" /> -->
      <div class="nav-links">
        <% if current_page?('/reigns') %>
          <div class="link link-1"><%= link_to "Back to the Kingdom of the Hill", '/' %></div>
        <%else%>
          <div class="link link-1"><%= link_to "History of all reigns of The Hill", "/reigns" %></div>
        <% end %>

        <% if current_user %>
          <div class="link link-2"><%= link_to "Sign out", signout_path %></div>
        <% end %>
      </div>
    </nav>

    <% unless current_page?('/reigns') %>
      <div class="current-reign-decl page-top">
        <div class="decl-top">
          <div class="decl-line-1">
            <div class="row">
            <div class="col-xs-12">
              <img class="crown crown-left" src="/assets/crown.png" alt="crown" />

              <h2 class="monarch-decl">
                <%= "#{current_monarch.title} #{current_monarch.first_name}" %>
              </h2>

              <img class="crown crown-right" src="/assets/crown.png" alt="crown" />
            </div>
          </div>

        </div>
          <h2 class="rule-decl">is ruling over the hill!</h2>
        </div>

        <div class="decl-bottom">
              <img class="monarch-picture" src="<%=current_monarch.picture%>" alt="current monarch" />
            </div>
              <p class="reign-number "> <%= "Reign # #{current_reign.id} "%></p>
            <span class="created_at"><%= "#{current_reign.created_at.to_f}"%></span>
            <div class="timer"></div>
            <p class="previous-ruler">Previous ruler: <span class="very-highlight"><%= (User.find(previous_reign.user_id)).first_name %></span>, defeated with: <span class="very-highlight"><i><%=current_reign.weapon%></i></span></p>
      </div>

    <% end %>

    <%= yield %>


  <% unless current_page?('/reigns') %>
    <div class="top-ten-container">
      <div class="hp-title">
        <img src="/assets/trophy.png" class="top-icon crown-left" alt="" />
        <h3 class="h3-title">Top 10 monarchs</h3>
        <img src="/assets/trophy.png" class="top-icon crown-right" alt="" />
      </div>

      <div class="top-tenz">
        <div class="top-ten by-reign-number">
          <p class="top-subtitle">By number of reigns</p>
          <% top_ten_by_reign_number.each_with_index do |monarch, index| %>
            <div class="top-li back-color1">
              <img class="top-monarch-picture" src="<%=monarch.picture%>" alt="picture of top monarch" />
              <div class="rank-info info-top">
                <div class="rank-top">
                  <div class="top-index"><%="##{(index+1)} - "%></div>
                  <div class="top-name"><%= "#{monarch.title} #{monarch.first_name}" %></div>
                </div>
                <div class="rank-bottom">
                  <%= "#{monarch.reigns_count} reigns" %>
                </div>
              </div>
            </div>
            <br>
          <% end %>
        </div>

        <div class="top-ten by-duration">
          <p class="top-subtitle">By total time ruled over the hill</p>
          <% top_ten_by_duration.each_with_index do |monarch, index| %>
            <div class="top-li back-color2">
              <img class="top-monarch-picture" src="<%=monarch.picture%>" alt="picture of top monarch" />
              <div class="rank-info info-top">
                <div class="rank-top">
                  <div class="top-index"><%="##{(index+1)} - "%></div>
                  <div class="top-name"><%= "#{monarch.title} #{monarch.first_name}"%></div>
                </div>
                <div class="rank-bottom">
                  <%="#{humanize(monarch.total_reign)}" %>
                </div>
              </div>
            </div>
            <br>
          <% end %>
        </div>

      </div>

    </div>
  <% end %>

  </body>
</html>

app/views/refuse/index.html.erb
<div class="out-message">
  <p>Hey!</p>
  <p>
    It seems that that you don't deserve the throne..
  </p>


  <p>
    Here's for you:
  </p>

  <iframe width="560" height="315" src="https://www.youtube.com/embed/cMuNlAIJFog" frameborder="0" allowfullscreen class=politeness-video></iframe>
  <br>
  <p>
    Let us know on the Facebook Page when you know the song by heart! :-)
  </p>
 <br>
  <p>
    Faithfully,
  </p>

  <p>
    The royal moderators of the peaceful Kingdom of the Hill
  </p>
</div>

app/views/reigns/_reign.html.erb
<div class="monarch-container reign">
    <img class="top-monarch-picture reign-picture" src="<%=reign.user.picture%>" alt="picture of monarch" />
    <div class="rank-info">
      <div class="rank-top">
        <div class="top-index"><%="##{reign.id} - "%></div>
        <div class="top-name">
          <%= "#{reign.user.title} #{reign.user.first_name}"%>
        </div>
      </div>
      <div class="rank-bottom">
        <div class="reign-dates">
          <%="From #{reign.created_at.to_formatted_s(:long_ordinal)}"%>
          <% unless reign.finished == nil%>
            <%="until #{reign.finished.to_formatted_s(:long_ordinal)} (GMT)" %>
          <% end %>
        </div>
        <div class="reign-duration">
          <% if reign.finished == nil %>
          <div class="current-reign-duration">
            still on
          </div>
          <%else%>
            <img src="assets/clock.png" class="history-icon" alt=""/>
            <%="#{humanize(reign.duration)}"%>
          <% end %>
        </div>
        <div class="reign-weapon">
          <img src="assets/sword.png" class="history-icon" alt="" />
          <%="#{reign.weapon}"%>
        </div>
      </div>
    </div>
</div>

app/views/reigns/index.html.erb
<div class="kingdom-history page-top">
  <h2 class="history-title">The history of the Kingdom of the Hill</h2>
  <h3 class="history-subtitle">All reigns in reverse chronological order</h3>

    <div class="reigns" id="reigns">
      <div class="page">
        <%= render @reigns %>
      </div>
    </div>
  </div>
<%= paginate @reigns %>

app/views/reigns/index.js.erb
$("#reigns").append("<div class='page'><%= escape_javascript(render(@reigns)) %></div>");

app/views/users/index.erb
<div class="personal-message">
  <div class="content">
    <h4 class="salutation">
      <% if current_user == current_monarch %>
        <%= current_user.title %>
      <% end %>
      <%= "#{current_user.first_name}," %> </h4>

      <% if current_user == current_monarch %>
        <p class="compliment-or-call-to-action line-one">Yeah...that's right. YOU are ruling over the hill!</p>
        <img src="/assets/gif-<%=random_number%>.gif" alt="celebration" class="gif"/>
        <p class="compliment-or-call-to-action line-two">
          You've conquered the throne with such virtuosity. So much royalty in you..
        </p>
      <% else %>
        <% if current_user.total_reign <= 0 %>
          <p class="compliment-or-call-to-action line-one">Welcome to the Kingdom of the Hill!</p>
          <p class="compliment-or-call-to-action line-two">Hope you're enjoying the royal feeling...</p>
        <% else %>
          <p class="compliment-or-call-to-action line-one">
            You are no longer ruling over the hill. You've been usurped by
            <span class="highlight"><%= "#{usurper.title} #{usurper.first_name}" %></span> with:
            <span class="highlight"><%= "#{deadly_weapon}" %></span>.
          </p>
          <p class="compliment-or-call-to-action line-two">
            But the throne is warm and waiting for you to come back..
          </p>
        <% end %>
        <div class="action">
          <p class="compliment-or-call-to-action">Choose your <strong>weapon</strong> to conquer the throne:</p>
          <div class="royal-form">
            <%= form_for [@reign] do |f| %>
              <%= f.text_field :weapon, required: true %>
              <br>
            <%= f.submit "Take over the throne", :class => "button take-over hp-link" %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
</div>

<% if current_user.total_reign >0 %>

  <div class="user-stats">
    <div class="hp-title">
      <img src="/assets/ranking.png" class="top-icon crown-left stat-icon" alt="" />
      <h3 class="h3-title">Your royal stats</h3>
        <img src="/assets/ranking.png" class="top-icon crown-right stat-icon" alt="" />
    </div>

      <div class="stat-content">
      <p class="p-stats">In total, you have ruled <span class="highlight"><% reigns = Reign.where.not(finished: nil).where(user_id: current_user.id) %>
        <%= reigns.length %>
        times</span> over the hill, for a total duration of <span class="highlight"><%= humanize(current_user.total_reign) %></span>. <br> Your global rank is:</p>

      <!-- <p class="p-stats">Your global rank is:</p> -->
      <div class="user-ranking-container">

          <div class="stat-info">
            <div class="user-rank back-color1"><%= "##{current_user.ranking_by_reign_number}" %></div>
            <p class="by-p">by number of reigns</p>
          </div>

          <div class="stat-info">
            <div class="user-rank back-color2"><%= "##{current_user.ranking_by_duration}" %></div>
            <p class="by-p">by total reign duration</p>
          </div>
      </div>
      </div>
  </div>
<% end %>

<!-- <div class="sharing">
    <h3 class="h3-sharing">Sharing is ruling</h3>
    <%= social_share_button_tag("YEAH! I'm a monarch of the Kingdom of the Hill! #RulingOverTheHill") %>
</div> -->
<% if current_user == current_monarch%>
  <script type="text/javascript">
    reloadIfNewMonarch(<%=current_user.id%>)
  </script>
<% end %>

app/views/welcome/index.html.erb
<div class="button-wrapper">
  <button class="link-hp button"><%= link_to "Ascend the throne", "/auth/facebook", :class => "hp-link" %></button>
</div>